config_name: quantum_modl,k=10
description: "quantum config, k=10. Restore weights from <quantum_modl,k=1>"

n_layers: 5
k_iters: 3
epochs: 10

dataset_name: modl_dataset
dataset_params:
  dataset_path: 'data/dataset.hdf5'
  sigma: 0.01
val_data: False
batch_size: 1

model_name: quantum_modl

restore_weights: final #False, best, inter, final
restore_path: 'workspace/quantum_modl,k=1/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: True